### ISSUE TITLE
[W3C] Rework 2nd paragraph?

### ISSUE THREAD

**Issue by kakinney** [w3c/accessibility-intro#12]
I love this sentence: "Accessibility is essential for developers and organizations that want to create high-quality websites and web tools, and not exclude people from using their products and services."  but I think it's lost where it is.   Can we move it up to the 2nd paragraph?

"The impact of disability is radically changed on the Web because the Web removes barriers to communication and interaction that many people face in the physical world. Accessibility is essential for developers and organizations that want to create high-quality websites and web tools, and not exclude people from using their products and services. However, when websites, web technologies, or web tools are badly designed, they can unknowingly create barriers that exclude people from using the Web."

**Comment by shawna-slh** [comment]
It was supposed to provide a strong conclusion. :)

I've tried highlighting it a few different ways. Let's see how that works...

**Comment by shawna-slh** [comment]
I changed my mind and moved it to the top -- since I agree with you that it's a great point, and since many people are likely to read the top, but not get through the whole page.

I added it as a separate paragraph.
