### ISSUE TITLE
Duplicated repository?

### ISSUE THREAD

**Issue by yatil** [w3c/accessibility-intro#14]
I want to make sure that this is the current working repository that replaces https://github.com/w3c/wai-intro-accessibility.

If so, we can delete w3c/wai-intro-accessibility, as no work happened there, to avoid confusion.

**Comment by shawna-slh** [comment]
let's talk.

**Comment by yatil** [comment]
This is the repository for the W3C intro https://github.com/w3c/wai-intro-accessibility is for the intro of the WAI site.

**Comment by shawna-slh** [comment]
Clarification:)
This is the repository for the W3C intro (https://www.w3.org/standards/webdesign/accessibility)

For the WAI site intro (https://www.w3.org/WAI/intro/accessibility), the repository is:
     https://github.com/w3c/wai-intro-accessibility
