### ISSUE TITLE
[W3C] Use It links

### ISSUE THREAD

**Issue by shawna-slh** [w3c/accessibility-intro#2]
What do we want in the [Use It section](https://w3c.github.io/accessibility-intro/#useitrhs)?

Please see similar sections in W3C site sibling pages, e.g.,:
* [Internationalization](https://www.w3.org/standards/webdesign/i18n.html#curstatusrhs) has:
** Tutorials
** Tools
** Quick Tips
** More Resources
* [HTML & CSS](https://www.w3.org/standards/webdesign/htmlcss.html#useitrhs)
* [Mobile Web](https://www.w3.org/standards/webdesign/mobilweb.html#useitrhs)

**Comment by vmmiller** [comment]
- Planning and Managing
- Improving through Interim Repairs
- HTML & CSS
- Mobile Web

**Comment by shawna-slh** [comment]
I think we want accessibility-specific info only in this section.

I think we want a link to Evaluating/Testing Accessibility, among others...

**Comment by notabene** [comment]
I was puzzled by the title of the section in issue #1 and after reading this issue, I still find "Use it" vague and a bit hard to comprehend, but it seems it' a W3C idiosyncracy, so so be it ;)

So, at the time of writing my comment, here is its content:

- How People with Disabilities Use the Web
- Improving the Accessibility of Your Web Site
- Managing Accessibility
- Evaluating Web Accessibility

I would definitely add a link to [Business case](https://www.w3.org/WAI/bcase/) which is very useful for advocating and evangelizing.

**Comment by shawna-slh** [comment]
It's in the template for these types of W3C pages. Generally links to Tutorials and Tips for developer audience.

(May be not the best wording, but I think very low priority for us to bother with right now. :)

**Comment by notabene** [comment]
@slhenry Agreed :)
