### ISSUE TITLE
[WAI] same content for W3C main site and WAI subsite?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/accessibility-intro#3]
The [W3C page](https://www.w3.org/standards/webdesign/accessibility) was created for the W3C-specific audience that is largely developer and standards orientated -- and following a template for [sibling pages (linked under "WEB DESIGN AND APPLICATIONS")](https://www.w3.org/standards/webdesign/accessibility#w3c_logo_shadow).

Do we want essentially the same content for the WAI page? (probably minus some of the template info, e.g., "Current Status of Specifications" section)

Or do we want a different focus or emphasis for the WAI page?

(Obviously it would be simpler to have same content.)

If different, how would we define the different [Requirements](https://w3c.github.io/accessibility-intro/requirements)?

**Comment by nrhsinclair** [comment]
It seems to me that W3C page is both an introduction to accessibility and an introduction to WAI and thus, the WAI content should be different, more detailed, more comprehensive. If a user/individual is moving from W3C page to the WAI content they are seeking more in depth information.

**Comment by vmmiller** [comment]
I think you have two separate resources which are really valuable as they address two different groups of users speaking the language of those users very well.  

The W3C page seems to be focused for the developer and more technical audience and addresses those needs. The WAI page provides a more detailed introduction to accessibility which I find could be more convincing to an audience just learning about the subject matter.  It is a very good resource for the business case on accessibility. 

I would keep both resources as they address different audiences really well.

**Comment by notabene** [comment]
It seems to me that keeping two different contents is good and that what @nrhsinclair and @vmmiller say is relevant (yay ;)).

<del> I wonder, though, whether the W3C page is not somehow too detailed. What is its precise role? If it's an introduction, maybe there's too much of it and the WAI page could be the go-to page for further reference. (I'm not strongly attached to what I'm saying, just that the need for separate two pages is unclear to me if they have roughly the same content and I'd be grateful to have some clarification. Maybe it's just me being new to EOWG ;))</del>

<ins>I was wondering aloud, but @slhenry did well to ask me to provide specifics: re-reading it made me think that no, it's OK. </ins>

**Comment by shawna-slh** [comment]
Based on input, the plan (and [requirements](https://w3c.github.io/accessibility-intro/requirements)) has been revised to say that we will keep two different resources.

We'll leave this issue open a bit in case people will add more specific comments on the different requirements for the 2 resources.
