### ISSUE TITLE
[W3C] wording "badly designed"

### ISSUE THREAD

**Issue by nrhsinclair** [w3c/accessibility-intro#5]
[UPDATE: this comment moved to https://github.com/w3c/accessibility-intro/issues/6]

would suggest changing 
"The Web is fundamentally designed to work for all people, whatever their hardware, software, language, culture, location, or physical or mental ability...."

to 
"The Web is fundamentally an open platform designed to be used by all people, whatever their hardware, software, language, culture, location, or physical or mental ability..."

**Comment by nrhsinclair** [comment]
"badly designed" is vague, not clear
However, when websites, web technologies, or web tools are badly designed, they can create barriers that exclude people from using the Web.
suggest revision:
However, when websites, web technologies, or web tools are designed without adhering to web standards and guidelines, they can create barriers that exclude people from using the Web.

**Comment by vmmiller** [comment]
Suggestion on 2nd comment above, replace "adhering to" with "applying" (for simplicity).  No further comments on the page, good to go.

**Comment by shawna-slh** [comment]
Thanks for the input! I moved the first point to a separate issue https://github.com/w3c/accessibility-intro/issues/6 so they are easier to manage.

About "badly designed":

Simplified version of above is:
> However, when websites, web technologies, or web tools don't meet web standards, they can create barriers that exclude people from using the Web.

But I think that puts too much emphasis on web standards -- and lots of things that don't meet standards don't create accessibility barriers.

We wanted to contrast how the web is fundamentally designed and kinda get across, "If you don't do it right, you are bad for creating barriers" . We weren't trying to be too specific in this part.

Thoughts?

**Comment by Sylduch-Conseil** [comment]
I agree with @nrhsinclair's comment and @vmmiller's change from adhering to applying. 

I am also ok with @slhenry's simplified version. But I think that it is ok to say "then can create barriers", the word "can" does not mean that barriers are created. 
May be a suggestion to remove the idea that not applying web standards creates barriers could be: 

Original text: 
> However, when websites, web technologies, or web tools don't meet web standards, they can create barriers that exclude people from using the Web.

Replacing it with:

"However, when websites, web technologies, or web tools don't meet web standards, this can lead to barriers that exclude people from using the Web."

**Comment by nrhsinclair** [comment]
Sylvie's rewording does a nice job of stating the main point: using web content accessibility guidelines will help content creators and developers remove barriers that may otherwise be present if guidelines are not followed. I think that is more helpful than "badly designed".

**Comment by sharronrush** [comment]
I have a different perspective although I understand the point about the vagueness of the phrase.  I have always felt that "badly designed" was a deft way of saying that good design must be accessible to actually be "good." In the interests of brevity and the subtle message that accessibility is an integral part of good design, I would urge us to leave it as is.

**Comment by nrhsinclair** [comment]
Sounds good. I appreciate the consideration and have no need for further discussion.

**Comment by kakinney** [comment]
I agree with @sharronrush that we want to point out that accessibility is part of good design, I just feel like the word badly sounds scolding.  How about "poorly designed"?

**Comment by notabene** [comment]
> [UPDATE: this comment moved to https://github.com/w3c/accessibility-intro/issues/6]

I would suggesst closing this issue then @nrhsinclair

**Comment by shawna-slh** [comment]
We kinda did want to be scolding. :-)
I think "badly designed" is stronger than "poorly designed".

Given "I would urge us to leave it as is" and "have no need for further discussion", I'm leaving it for now. We could revisit later if people want to talk through it.
