### ISSUE TITLE
[W3C] wording tweak first sentence

### ISSUE THREAD

**Issue by shawna-slh** [w3c/accessibility-intro#6]
From Norah https://github.com/w3c/accessibility-intro/issues/5#issue-245418257

> would suggest changing
"The Web is fundamentally designed to work for all people, whatever their hardware, software, language, culture, location, or physical or mental ability...."
to
"The Web is fundamentally an open platform designed to be used by all people, whatever their hardware, software, language, culture, location, or physical or mental ability..."

**Comment by shawna-slh** [comment]
changing:
>The Web is fundamentally designed to work for all people

to:
> The Web is fundamentally an open platform designed to be used by all people

would add significant complexity to an already complex sentence. While "open platform" is a buzz phrase that's good in some contexts, I don't know that we want it here?

Thoughts?

**Comment by Sylduch-Conseil** [comment]
I understand Nora's comment, but it is true that the new proposal is a bit too complicate to read. What about deleting platform? 
This would be: "The Web is fundamentally designed to be used by all people"

**Comment by nrhsinclair** [comment]
Yes, I think Sylvie's suggestion removes the added complexity and keeps the focus on the user experience.  It is the phrase "fundamentally designed to work for all people" that seems somewhat problematic. It seems to me, web is designed to be used by all people, but will only work for all people if accessibility is addressed. (editor's discretion).

**Comment by shawna-slh** [comment]
Thanks for the input!

I agree with "but will only work for all people if accessibility is addressed" -- that's the point. :-)

> The Web is fundamentally designed to work for all people.... When the Web meets this goal, it is accessible to people [with disabilities]

Thanks much for clarifying "editor's discretion". I'd like to leave it for now, and when we have more time, we can revisit if we want.
