### ISSUE TITLE
[W3C][editor's discretion] 'W3C technical specifications' link to discontinued WG

### ISSUE THREAD

**Issue by notabene** [w3c/accessibility-intro#8]
Line 152 of https://github.com/w3c/accessibility-intro/blob/master/index.html#L152

```
<p>WAI's coverage of web accessibility includes '<a href="http://www.w3.org/WAI/intro/wcag.php">web content</a>' (websites and web applications), <a href="http://www.w3.org/WAI/intro/atag.php">authoring tools</a> (such as content management systems (CMS) and blog software), browsers and other '<a href="http://www.w3.org/WAI/intro/uaag.php">user agents</a>', and <a href="http://www.w3.org/WAI/PF/">W3C technical specifications</a>, including <a href="http://www.w3.org/WAI/intro/aria.php">WAI-ARIA</a> for accessible rich Internet applications.</p>
```

The link 'W3C technical specifications' points to the WAI PFWG which is discontinued.

Proposed:
s/
`and <a href="http://www.w3.org/WAI/PF/">W3C technical specifications</a>, including <a href="http://www.w3.org/WAI/intro/aria.php">WAI-ARIA</a> for accessible rich Internet applications.`
/
`and W3C technical specifications, including <a href="http://www.w3.org/WAI/intro/aria.php">WAI-ARIA</a> for accessible rich Internet applications and <a href="https://www.w3.org/WAI/APA/">APA</a> for accessible platform architectures.`
/

**Comment by shawna-slh** [comment]
Deleted it, thanks!
